language: ruby
rvm:
  - 2.3.0
services:
  - mysql
before_script:
  - cp config/database.yml.sample config/database.yml
  - mysql -e 'create database spread_here_test;'
install: bundle install --path vendor/bundle --binstubs vendor/bundle/bin
script: 
  - RAILS_ENV=test bundle exec rake db:create db:migrate && bundle exec rake
  - RAILS_ENV=test bundle exec rake
