language: ruby
rvm:
  - 2.5.7
  - ruby-head
services:
  - mysql
  - redis-server

before_script:
  - cp config/database.yml.sample config/database.yml
  - mysql -e 'create database spread_here_test;'
install: bundle install --path vendor/bundle --binstubs vendor/bundle/bin
script: 
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - RAILS_ENV=test bundle exec rake test
