default:
  host: localhost
  port: 6379
development:
  db: 0
  namespace: flea_dev
test:
  db: 1
  namespace: flea_test
production:
  db: 2
  host: <%= ENV["redis_url"] %>
  namespace: flea_production
